### ISSUE TITLE
404 page on embeded app

### ISSUE THREAD

**Issue by pbrink231** [Shopify/shopify-node-app#106]
Hello, I am having an issue that I dont understand or how to track it down.

Fresh install.  Shop is authenticated.  I then get forwarded to the embeded app inside the store admin page.

The page shows my app name at the top.  then it shows this as the page:

```
Not Found
404
Error: Not Found
    at C:\Users\user\Desktop\git repos\shopify-team-node\server\index.js:129:15
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\@shopify\shopify-express\node_modules\express\lib\router\index.js:635:15
    at next (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\@shopify\shopify-express\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\@shopify\shopify-express\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\@shopify\shopify-express\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\express\lib\router\index.js:275:10)
    at middleware (C:\Users\user\Desktop\git repos\shopify-team-node\node_modules\webpack-hot-middleware\middleware.js:26:48)
```

I am using ngrok for forwarding which worked fine because everything was athenticated.  I see the requests coming in on the terminal which is sending 404.

How can I debug this.  I am unsure where the problem is at the moment.

Thank you.

**Comment by pbrink231** [comment]
Bad setup for my app url.  please ignore.
