### ISSUE TITLE
Cannot install on Ubuntu

### ISSUE THREAD

**Issue by NikolaiT** [Shopify/shopify-node-app#130]
Cant install with yarn, sqlite seems to break.

```
yarn install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @shopify/shopify-express > sqlite3 > node-pre-gyp > hawk > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning @shopify/shopify-express > sqlite3 > node-pre-gyp > hawk > boom > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning @shopify/shopify-express > sqlite3 > node-pre-gyp > hawk > sntp > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[3/5] Fetching packages...
[---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/1056(node:5192) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > react-object-inspector@0.2.1" has incorrect peer dependency "react@^0.14.0".
[5/5] Building fresh packages...
[1/2] ⠐ sqlite3
error /home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.9.0 | linux | x64
node-pre-gyp info check checked for "/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.9.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http getaddrinfo EAI_AGAIN mapbox-node-binary.s3.amazonaws.com mapbox-node-binary.s3.amazonaws.com:443 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.9.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.9.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nikolai/.node-gyp/10.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/nikolai/.node-gyp/10.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/nikolai/.node-gyp/10.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.9.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3VXPrintf’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:25065:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
         flag_long = sizeof(char*)==sizeof(long int);
         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:25067:7: note: here
       case etORDINAL:
       ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3GetToken’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137154:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( !sqlite3Isdigit(z[1]) )
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137163:5: note: here
     case CC_DIGIT: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137253:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( z[1]=='\'' ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137267:5: note: here
     case CC_ID: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3ExprCodeTarget’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:93034:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case TK_AGG_COLUMN: {
                         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:93047:5: note: here
     case TK_COLUMN: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘resolveP2Values’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:71026:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
           if( pOp->p2!=0 ) p->readOnly = 0;
             ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:71029:9: note: here
         case OP_AutoCommit:
         ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘fkActionTrigger’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:107247:11: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if( !pChanges ){
           ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:107251:7: note: here
       default:
       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3GenerateConstraintChecks’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:108736:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
         onError = OE_Abort;
                 ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:108739:7: note: here
       case OE_Rollback:
       ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3VdbeExec’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78202:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
   if( (pIn3->flags & MEM_Null)==0 ) break;
     ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78236:1: note: here
 case OP_Halt: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78367:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
   if( pOp->p1>db->aLimit[SQLITE_LIMIT_LENGTH] ){
     ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78386:1: note: here
 case OP_String: {          /* out2 */
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78941:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
   pOp->opcode = OP_Function;
               ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78944:1: note: here
 case OP_Function: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:82140:38: warning: this statement may fall through [-Wimplicit-fallthrough=]
   p->aCounter[SQLITE_STMTSTATUS_SORT]++;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:82155:1: note: here
 case OP_Rewind: {        /* jump */
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:83361:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
   pOp->opcode = OP_AggStep;
               ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:83364:1: note: here
 case OP_AggStep: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘fts3SnippetFunc’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146657:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 6: nToken = sqlite3_value_int(apVal[5]);
             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146658:5: note: here
     case 5: iCol = sqlite3_value_int(apVal[4]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146658:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 5: iCol = sqlite3_value_int(apVal[4]);
             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146659:5: note: here
     case 4: zEllipsis = (const char*)sqlite3_value_text(apVal[3]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146659:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 4: zEllipsis = (const char*)sqlite3_value_text(apVal[3]);
             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146660:5: note: here
     case 3: zEnd = (const char*)sqlite3_value_text(apVal[2]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146660:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 3: zEnd = (const char*)sqlite3_value_text(apVal[2]);
             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146661:5: note: here
     case 2: zStart = (const char*)sqlite3_value_text(apVal[1]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘rtreeNonleafConstraint’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:162310:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( p->op!=RTREE_EQ ) break;  /* RTREE_LE and RTREE_LT end here */
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:162313:5: note: here
     default: /* RTREE_GT or RTREE_GE,  or fallthrough of RTREE_EQ */
     ^~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonRenderNode’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176768:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( pNode->jnFlags & JNODE_RAW ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176774:5: note: here
     case JSON_REAL:
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonReturn’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176891:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       int_as_real: /* fall through to real */;
       ^~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176893:5: note: here
     case JSON_REAL: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonEachColumn’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:178258:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( p->bRecursive ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:178268:5: note: here
     case JEACH_ROOT: {
     ^~~~
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../../nan/nan.h:192:0,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../src/database.h:10:0,
                 from ../src/database.cc:4:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
/home/nikolai/.node-gyp/10.9.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/nikolai/.node-gyp/10.9.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/database.h:10:0,
                 from ../src/database.cc:4:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
/home/nikolai/.node-gyp/10.9.0/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/nikolai/.node-gyp/10.9.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/database.h:10:0,
                 from ../src/database.cc:4:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
/home/nikolai/.node-gyp/10.9.0/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/nikolai/.node-gyp/10.9.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/database.h:10:0,
                 from ../src/database.cc:4:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../../nan/nan.h:49:0,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
/home/nikolai/.node-gyp/10.9.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/nikolai/.node-gyp/10.9.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)’:
../src/database.cc:144:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^~~~~~
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)’:
../src/database.cc:230:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^~~~~~
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)’:
../src/database.cc:525:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^~~~~~
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)’:
../src/database.cc:625:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^~~~~~
node_sqlite3.target.mk:121: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory '/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.18.5-041805-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/lib/binding/node-v64-linux-x64"
gyp ERR! cwd /home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/lib/binding/node-v64-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Linux 4.18.5-041805-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/nikolai/projects/work/new_smilemeup/shopify/cashpresso/shopify-node-app/node_modules/sqlite3/lib/binding/node-v64-linux-x64' (1)
```

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
