### ISSUE TITLE
yarn install dies on v8-profiler

### ISSUE THREAD

**Issue by jamiemtdwyer** [Shopify/shopify-node-app#65]
Console dump:

```
╭─jamied@hyperion  ~/dev/shopify-node-app  ‹master›
╰─$ yarn install                                                                     1 ↵
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "webpack > ajv-keywords@1.5.1" has unmet peer dependency "ajv@>=4.10.0".
[5/5] 📃  Building fresh packages...
[-/4] ⠐ waiting...
[-/4] ⠐ waiting...
[3/4] ⠐ v8-debug: http GET https://node-inspector.s3.amazonaws.com/debug/v1.0.1/
[4/4] ⠐ v8-profiler: http GET https://node-inspector.s3.amazonaws.com/profiler/v
error /Users/jamied/dev/shopify-node-app/node_modules/v8-profiler: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/jamied/dev/shopify-node-app/node_modules/v8-profiler
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@8.9.1 | darwin | x64
node-pre-gyp info check checked for "/Users/jamied/dev/shopify-node-app/node_modules/v8-profiler/build/profiler/v5.7.0/node-v57-darwin-x64/profiler.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@8.9.1 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jamied/dev/shopify-node-app/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.9.1/bin/node" "/Users/jamied/dev/shopify-node-app/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jamied/dev/shopify-node-app/node_modules/v8-profiler
node-pre-gyp ERR! node -v v8.9.1
```

`yarn cache clean` didn't fix for me.

Removing `node-inspector` from package.json was the only thing that worked for me.

**Comment by cparadigm** [comment]
Looks like node v6.x is the solution to this issue on OS X.
https://github.com/node-inspector/node-inspector/issues/960

But then you cannot install because of error shopify-node-app@0.0.0: The engine "node" is incompatible with this module. Expected version ">= 8.1.0".

**Comment by LucasMaliszewski** [comment]
Looks like node v6.x is the solution to this issue on OS X.
node-inspector/node-inspector#960

But then you cannot install because of error shopify-node-app@0.0.0: The engine "node" is incompatible with this module. Expected version ">= 8.1.0".
