### ISSUE TITLE
secret option required for sessions

### ISSUE THREAD

**Issue by LucasMaliszewski** [Shopify/shopify-node-app#66]
After following the guides instructions. There seems to be a disconnect with the service. I've built the simple application that Shopify provides [here](https://help.shopify.com/api/tutorials/building-node-app) with success. However, when running yarn run start|dev, and after having to remove npm-inspector from the settings.json, I'm left with:

```
secret option required for sessions

Error: secret option required for sessions
    at session (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express-session/index.js:199:12)
    at Layer.handle [as handle_request] (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:317:13)
    at /Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:335:12)
    at next (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/Applications/MAMP/htdocs/shopify-node-app/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:317:13)
    at /Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:335:12)
    at next (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/Applications/MAMP/htdocs/shopify-node-app/node_modules/body-parser/lib/types/json.js:103:7)
    at Layer.handle [as handle_request] (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:317:13)
    at /Applications/MAMP/htdocs/shopify-node-app/node_modules/express/lib/router/index.js:284:7
```

The .env has the correct keys added and URL being forwarded by ngrok. So I'm not sure what this is being caused by.

**Comment by LucasMaliszewski** [comment]
Non-issue. Was able to identify the issue and resolve.
