### ISSUE TITLE
main.js error after install

### ISSUE THREAD

**Issue by mandyschippers** [Shopify/shopify-node-app#82]
After installing the app, the following errors are displayed:

GET https://886af3d7.ngrok.io/assets/main.js net::ERR_CONTENT_LENGTH_MISMATCH
jquery.min.js:2 

Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://fyndle-favorites.myshopify.com" from accessing a cross-origin frame.
    at contents (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5166)
    at Function.map (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14863)
    at oe.fn.init.oe.fn.(anonymous function) [as contents] (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5282)
    at HTMLIFrameElement.eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:2037)
    at Function.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14055)
    at oe.fn.init.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:11918)
    at e.bindActivityDetectors (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1853)
    at e.init (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/ActivityMonitorController.js:1:257)
    at onLoaded (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/content.js:1:979)
    at eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/ComponentFactory.js:1:943)

App URL where this occurs:

https://fyndle-favorites.myshopify.com/admin/apps/2520896c910c08e6ad606d30c15bf348/?hmac=491bed9aca25060f263856eff3ad4e8ef4861a45c62cb72defa737056c24c894&locale=en&protocol=https%3A%2F%2F&shop=fyndle-favorites.myshopify.com&timestamp=1514584220

Is this related to the node modules installed or the yarn installation instructions? I have cloned the repo today and have followed installation instructions to the letter.

**Comment by DevCabin** [comment]
I'm getting the same error.

**Comment by shesko** [comment]
Could you guys please check your node version? I had v8.1.4 and I encountered the same issue. However, after upgrading to v9.4.0 the error stopped occurring.

**Comment by DanWebb** [comment]
Can confirm updating node fixed things for me, seems to be to do with the keepAliveTimeout setting on the server in Node 8.0 - 8.4 as [this issue](https://github.com/expressjs/express/issues/3392) explains in more detail.

If you don't want to update node for whatever reason you could add something like `server.keepAliveTimeout = 120000 * 5;` to line 11 in /bin/www.js instead.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
